const { Client } = require('pg');

const connectionString = 'postgresql://postgres:Dadibdan92002@db.rrgnyeakceimlftxzaau.supabase.co:5432/postgres';

const client = new Client({
    connectionString,
    ssl: {
        rejectUnauthorized: false,
    },
});

async function setup() {
    try {
        await client.connect();
        console.log('Connected to database...');

        const createTableQuery = `
      CREATE TABLE IF NOT EXISTS blogs (
        id bigint generated by default as identity primary key,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        slug text not null,
        title text not null,
        content text not null,
        image_url text,
        unique(slug)
      );
    `;

        await client.query(createTableQuery);
        console.log('Table "blogs" created or already exists.');

        // Enable RLS
        await client.query(`ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;`);
        console.log('RLS enabled.');

        // Create Policy (Check if exists first to avoid error, or just drop and recreate)
        // Simpler: DO block
        const policyQuery = `
      DO $$
      BEGIN
          IF NOT EXISTS (
              SELECT 1
              FROM pg_policies
              WHERE tablename = 'blogs'
              AND policyname = 'Public blogs are viewable by everyone'
          ) THEN
              CREATE POLICY "Public blogs are viewable by everyone"
              ON blogs FOR SELECT
              USING ( true );
          END IF;
      END
      $$;
    `;

        await client.query(policyQuery);
        console.log('Read policy configured.');

        // Add some sample data if table is empty
        const countRes = await client.query('SELECT count(*) FROM blogs');
        if (parseInt(countRes.rows[0].count) === 0) {
            console.log('Table is empty. Inserting sample data...');
            const sampleQuery = `
         INSERT INTO blogs (slug, title, content, image_url)
         VALUES 
         ('welcome-geotuco', 'Welcome to GEOTUCO', 'We are excited to launch our new platform...', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb'),
         ('bienvenue-geotuco', 'Bienvenue chez GEOTUCO', 'Nous sommes ravis de lancer notre nouvelle plateforme...', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb');
       `;
            await client.query(sampleQuery);
            console.log('Sample data inserted.');
        }

    } catch (err) {
        console.error('Error setting up database:', err);
    } finally {
        await client.end();
    }
}

setup();
